// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// pf_barnes2014
NumericMatrix pf_barnes2014(NumericMatrix dem);
RcppExport SEXP _flowdem_pf_barnes2014(SEXP demSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type dem(demSEXP);
    rcpp_result_gen = Rcpp::wrap(pf_barnes2014(dem));
    return rcpp_result_gen;
END_RCPP
}
// pf_eps_barnes2014
NumericMatrix pf_eps_barnes2014(NumericMatrix dem);
RcppExport SEXP _flowdem_pf_eps_barnes2014(SEXP demSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type dem(demSEXP);
    rcpp_result_gen = Rcpp::wrap(pf_eps_barnes2014(dem));
    return rcpp_result_gen;
END_RCPP
}
// pf_watersheds_barnes2014
List pf_watersheds_barnes2014(NumericMatrix dem);
RcppExport SEXP _flowdem_pf_watersheds_barnes2014(SEXP demSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type dem(demSEXP);
    rcpp_result_gen = Rcpp::wrap(pf_watersheds_barnes2014(dem));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_flowdem_pf_barnes2014", (DL_FUNC) &_flowdem_pf_barnes2014, 1},
    {"_flowdem_pf_eps_barnes2014", (DL_FUNC) &_flowdem_pf_eps_barnes2014, 1},
    {"_flowdem_pf_watersheds_barnes2014", (DL_FUNC) &_flowdem_pf_watersheds_barnes2014, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_flowdem(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
