# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

pf_barnes2014 <- function(dem) {
    .Call(`_flowdem_pf_barnes2014`, dem)
}

pf_eps_barnes2014 <- function(dem) {
    .Call(`_flowdem_pf_eps_barnes2014`, dem)
}

pf_basins_barnes2014 <- function(dem) {
    .Call(`_flowdem_pf_basins_barnes2014`, dem)
}

comp_breach_lindsay2016 <- function(dem) {
    .Call(`_flowdem_comp_breach_lindsay2016`, dem)
}

d8_flow_directions <- function(dem) {
    .Call(`_flowdem_d8_flow_directions`, dem)
}

d8_flow_accum <- function(flowdirs) {
    .Call(`_flowdem_d8_flow_accum`, flowdirs)
}

d8_watershed_nested <- function(flowdirs, target_rc, nested) {
    .Call(`_flowdem_d8_watershed_nested`, flowdirs, target_rc, nested)
}

