# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Improved priority flood (algorithm 2) in:
#' "Barnes, R., Lehman, C., Mulla, D., 2014. Priority-flood: An optimal depression-filling and watershed-labeling algorithm for digital elevation models. Computers & Geosciences 62, 117–127. doi:10.1016/j.cageo.2013.04.024"
#'
#' @param dem The input digital elevation model (DEM)
#' @return The DEM with depressions removed
pf_barnes2014 <- function(dem) {
    .Call(`_flowdem_pf_barnes2014`, dem)
}

#' Improved priority flood (algorithm 3) in:
#' "Barnes, R., Lehman, C., Mulla, D., 2014. Priority-flood: An optimal depression-filling and watershed-labeling algorithm for digital elevation models. Computers & Geosciences 62, 117–127. doi:10.1016/j.cageo.2013.04.024"
#'
#' @param dem The input digital elevation model (DEM)
#' @return The DEM with depressions removed
pf_eps_barnes2014 <- function(dem) {
    .Call(`_flowdem_pf_eps_barnes2014`, dem)
}

#' Improved priority flood with watershed labels (algorithm 5) in:
#' "Barnes, R., Lehman, C., Mulla, D., 2014. Priority-flood: An optimal depression-filling and watershed-labeling algorithm for digital elevation models. Computers & Geosciences 62, 117–127. doi:10.1016/j.cageo.2013.04.024"
#'
#' @param dem The input digital elevation model (DEM)
#' @return List of two rasters: one with the filled input dem and one integer raster with basin labels
pf_basins_barnes2014 <- function(dem) {
    .Call(`_flowdem_pf_basins_barnes2014`, dem)
}

#' Complete breaching algorithm:
#' "Lindsay, J.B., 2016. Efficient hybrid breaching-filling sink removal methods for flow path enforcement in digital elevation models: Efficient Hybrid Sink Removal Methods for Flow Path Enforcement. Hydrological Processes 30, 846--857. doi:10.1002/hyp.10648"
#' As implemented in RichDEM
#'
#' @param dem The input digital elevation model (DEM)
#' @return The DEM with depressions breached
comp_breach_lindsay2016 <- function(dem) {
    .Call(`_flowdem_comp_breach_lindsay2016`, dem)
}

#' Function for determining d8 flow directions (RichDEM)
#'
#' @param dem The input digital elevation model (DEM)
#' @return a d8 flow direction raster
d8_flow_directions <- function(dem) {
    .Call(`_flowdem_d8_flow_directions`, dem)
}

#' Function for determining d8 flow accumulation (RichDEM)
#'
#' @param flowdirs The d8 pointer flow direction raster
#' @return a flow accumulation raster
d8_flow_accum <- function(flowdirs) {
    .Call(`_flowdem_d8_flow_accum`, flowdirs)
}

#' Function for d8 watersheds to a target area identified by row-col indexes
#' Potentially with labeling of nested watersheds
#'
#' @param flowdirs The d8 pointer flow direction raster
#' @param target_rc The outlet
#' @param nested Boolean
#' @return a flow accumulation raster
d8_watershed_nested <- function(flowdirs, target_rc, nested) {
    .Call(`_flowdem_d8_watershed_nested`, flowdirs, target_rc, nested)
}

