# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

pf_barnes2014 <- function(dem) {
    .Call(`_flowdem_pf_barnes2014`, dem)
}

pf_eps_barnes2014 <- function(dem) {
    .Call(`_flowdem_pf_eps_barnes2014`, dem)
}

pf_watersheds_barnes2014 <- function(dem) {
    .Call(`_flowdem_pf_watersheds_barnes2014`, dem)
}

